/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../routes/__root'
import { Route as SidebarRouteRouteImport } from './../routes/_sidebar/route'
import { Route as IndexRouteImport } from './../routes/index'
import { Route as SidebarSummaryRouteImport } from './../routes/_sidebar/summary'
import { Route as SidebarRobotSiteMapRouteImport } from './../routes/_sidebar/robot-site-map'
import { Route as SidebarProfileRouteImport } from './../routes/_sidebar/profile'
import { Route as SidebarMaintenanceRouteImport } from './../routes/_sidebar/maintenance'
import { Route as SidebarGenieRouteImport } from './../routes/_sidebar/genie'

const SidebarRouteRoute = SidebarRouteRouteImport.update({
  id: '/_sidebar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SidebarSummaryRoute = SidebarSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarRobotSiteMapRoute = SidebarRobotSiteMapRouteImport.update({
  id: '/robot-site-map',
  path: '/robot-site-map',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarProfileRoute = SidebarProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarMaintenanceRoute = SidebarMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => SidebarRouteRoute,
} as any)
const SidebarGenieRoute = SidebarGenieRouteImport.update({
  id: '/genie',
  path: '/genie',
  getParentRoute: () => SidebarRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/genie': typeof SidebarGenieRoute
  '/maintenance': typeof SidebarMaintenanceRoute
  '/profile': typeof SidebarProfileRoute
  '/robot-site-map': typeof SidebarRobotSiteMapRoute
  '/summary': typeof SidebarSummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/genie': typeof SidebarGenieRoute
  '/maintenance': typeof SidebarMaintenanceRoute
  '/profile': typeof SidebarProfileRoute
  '/robot-site-map': typeof SidebarRobotSiteMapRoute
  '/summary': typeof SidebarSummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_sidebar': typeof SidebarRouteRouteWithChildren
  '/_sidebar/genie': typeof SidebarGenieRoute
  '/_sidebar/maintenance': typeof SidebarMaintenanceRoute
  '/_sidebar/profile': typeof SidebarProfileRoute
  '/_sidebar/robot-site-map': typeof SidebarRobotSiteMapRoute
  '/_sidebar/summary': typeof SidebarSummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/genie'
    | '/maintenance'
    | '/profile'
    | '/robot-site-map'
    | '/summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/genie'
    | '/maintenance'
    | '/profile'
    | '/robot-site-map'
    | '/summary'
  id:
    | '__root__'
    | '/'
    | '/_sidebar'
    | '/_sidebar/genie'
    | '/_sidebar/maintenance'
    | '/_sidebar/profile'
    | '/_sidebar/robot-site-map'
    | '/_sidebar/summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SidebarRouteRoute: typeof SidebarRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_sidebar': {
      id: '/_sidebar'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SidebarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sidebar/summary': {
      id: '/_sidebar/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SidebarSummaryRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/robot-site-map': {
      id: '/_sidebar/robot-site-map'
      path: '/robot-site-map'
      fullPath: '/robot-site-map'
      preLoaderRoute: typeof SidebarRobotSiteMapRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/profile': {
      id: '/_sidebar/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof SidebarProfileRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/maintenance': {
      id: '/_sidebar/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof SidebarMaintenanceRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
    '/_sidebar/genie': {
      id: '/_sidebar/genie'
      path: '/genie'
      fullPath: '/genie'
      preLoaderRoute: typeof SidebarGenieRouteImport
      parentRoute: typeof SidebarRouteRoute
    }
  }
}

interface SidebarRouteRouteChildren {
  SidebarGenieRoute: typeof SidebarGenieRoute
  SidebarMaintenanceRoute: typeof SidebarMaintenanceRoute
  SidebarProfileRoute: typeof SidebarProfileRoute
  SidebarRobotSiteMapRoute: typeof SidebarRobotSiteMapRoute
  SidebarSummaryRoute: typeof SidebarSummaryRoute
}

const SidebarRouteRouteChildren: SidebarRouteRouteChildren = {
  SidebarGenieRoute: SidebarGenieRoute,
  SidebarMaintenanceRoute: SidebarMaintenanceRoute,
  SidebarProfileRoute: SidebarProfileRoute,
  SidebarRobotSiteMapRoute: SidebarRobotSiteMapRoute,
  SidebarSummaryRoute: SidebarSummaryRoute,
}

const SidebarRouteRouteWithChildren = SidebarRouteRoute._addFileChildren(
  SidebarRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SidebarRouteRoute: SidebarRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
